#!/bin/bash

pull() {
	_module_name=$1
	_module_path=$2
	_module_url=$3
	shift 3
	_args=$@

	if [ -d $_module_path ]
	then
        cd $_module_path
        git pull ${_args[*]}
	else
        echo "${SRED}Module \"$_module_name\" not found ($_dir)"
        echo -n "Use \"rgit prepare -d $_module_name\"${SRESET}"
        echo "${SRED}${STOEND}[fail]${SRESET}"
    fi
}