#!/bin/bash

start_task() {
	_module_name=$1
	_module_path=$2
	_module_url=$3
	shift 3
	_args=$@
	_new_branch=${_args[0]}

	if [ -z $_new_branch ]
	then
		echo -n "${SRED}Branch name not found${SRESET}"
		echo "${SRED}${STOEND}[fail]${SRESET}"
		print_help 'start-task'
	else
		cd $_module_path

		_main_branch=`git branch | grep develop | sed 's/[\.* ]//g'`
		if [ -z $_main_branch ]
		then
			_main_branch=`git branch | grep master | sed 's/[\.* ]//g'`
		fi
		if [ -z $_main_branch ]
		then
			echo -n "${SRED}Something wrong! Branch develop or master doesn\'t exist${SRESET}"
			echo "${SRED}${STOEND}[fail]${SRESET}"
		else
			#echo "${SGREEN}Checkout on $_main_branch${SRESET}"
			#_output=$(git checkout $_main_branch)

			echo "${SGREEN}Pull changes from $_main_branch${SRESET}"
			`git pull origin $_main_branch` > _otput

			#echo "${SGREEN}Checkout on $_new_branch${SRESET}"
			#_output=$(git checkout -b $_new_branch)

            #_is=`echo $_output | grep fatal | sed 's/[\.* ]//g'`
            #echo $_is
			echo "111111111${SMAGENTA}${_output}${SRESET}"

			echo "${SGREEN}${STOEND}[OK]${SRESET}"
		fi
	fi

}